// Demo data for testing search functionality
export const demoListings = [
  {
    id: '1',
    name: 'Mario\'s Italian Restaurant',
    description: 'Authentic Italian cuisine with fresh pasta and wood-fired pizza. Family-owned restaurant serving the community for over 20 years.',
    slug: 'marios-italian-restaurant',
    street: '123 Main Street',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    latitude: 40.7589,
    longitude: -73.9851,
    phone: '(555) 123-4567',
    email: 'info@mariositalian.com',
    website: 'https://mariositalian.com',
    images: ['/images/restaurant1.jpg'],
    categories: ['restaurants', 'italian', 'pizza'],
    tags: ['family-friendly', 'romantic', 'outdoor-seating'],
    features: ['takeout', 'delivery', 'reservations'],
    amenities: ['parking', 'wifi', 'wheelchair-accessible'],
    pricingRange: 'MODERATE',
    averageRating: 4.5,
    reviewCount: 127,
    isSponsored: true,
    sponsoredRank: 1,
    sponsoredTier: 'GOLD',
    status: 'PUBLISHED',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T15:30:00Z',
  },
  {
    id: '2',
    name: 'Downtown Coffee House',
    description: 'Cozy coffee shop with locally roasted beans, fresh pastries, and a welcoming atmosphere for work or relaxation.',
    slug: 'downtown-coffee-house',
    street: '456 Broadway',
    city: 'New York',
    state: 'NY',
    zipCode: '10013',
    latitude: 40.7505,
    longitude: -73.9934,
    phone: '(555) 234-5678',
    email: 'hello@downtowncoffee.com',
    website: 'https://downtowncoffee.com',
    images: ['/images/coffee1.jpg'],
    categories: ['coffee', 'cafe', 'breakfast'],
    tags: ['wifi', 'study-friendly', 'local'],
    features: ['takeout', 'mobile-ordering', 'loyalty-program'],
    amenities: ['wifi', 'outdoor-seating', 'parking'],
    pricingRange: 'BUDGET',
    averageRating: 4.2,
    reviewCount: 89,
    isSponsored: false,
    status: 'PUBLISHED',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-18T12:00:00Z',
  },
  {
    id: '3',
    name: 'Elite Hair Salon',
    description: 'Full-service hair salon offering cuts, color, styling, and treatments. Expert stylists with the latest techniques.',
    slug: 'elite-hair-salon',
    street: '789 Fifth Avenue',
    city: 'New York',
    state: 'NY',
    zipCode: '10022',
    latitude: 40.7614,
    longitude: -73.9776,
    phone: '(555) 345-6789',
    email: 'appointments@elitehair.com',
    website: 'https://elitehair.com',
    images: ['/images/salon1.jpg'],
    categories: ['beauty', 'hair-salon', 'spa'],
    tags: ['luxury', 'appointments-only', 'experienced'],
    features: ['online-booking', 'consultations', 'color-specialist'],
    amenities: ['parking', 'wheelchair-accessible', 'wifi'],
    pricingRange: 'EXPENSIVE',
    averageRating: 4.8,
    reviewCount: 156,
    isSponsored: true,
    sponsoredRank: 2,
    sponsoredTier: 'SILVER',
    status: 'PUBLISHED',
    createdAt: '2024-01-05T14:00:00Z',
    updatedAt: '2024-01-22T11:15:00Z',
  },
  {
    id: '4',
    name: 'Quick Fix Auto Repair',
    description: 'Reliable auto repair shop specializing in quick fixes, oil changes, and comprehensive vehicle maintenance.',
    slug: 'quick-fix-auto-repair',
    street: '321 Industrial Blvd',
    city: 'Brooklyn',
    state: 'NY',
    zipCode: '11201',
    latitude: 40.6892,
    longitude: -73.9442,
    phone: '(555) 456-7890',
    email: 'service@quickfixauto.com',
    website: 'https://quickfixauto.com',
    images: ['/images/auto1.jpg'],
    categories: ['automotive', 'repair', 'maintenance'],
    tags: ['quick-service', 'certified', 'warranty'],
    features: ['while-you-wait', 'shuttle-service', 'estimates'],
    amenities: ['waiting-area', 'parking', 'wifi'],
    pricingRange: 'MODERATE',
    averageRating: 4.3,
    reviewCount: 203,
    isSponsored: false,
    status: 'PUBLISHED',
    createdAt: '2024-01-08T08:00:00Z',
    updatedAt: '2024-01-19T16:45:00Z',
  },
  {
    id: '5',
    name: 'Smile Dental Care',
    description: 'Modern dental practice offering comprehensive oral health care with the latest technology and gentle approach.',
    slug: 'smile-dental-care',
    street: '654 Park Avenue',
    city: 'New York',
    state: 'NY',
    zipCode: '10065',
    latitude: 40.7736,
    longitude: -73.9566,
    phone: '(555) 567-8901',
    email: 'appointments@smiledentalcare.com',
    website: 'https://smiledentalcare.com',
    images: ['/images/dental1.jpg'],
    categories: ['healthcare', 'dental', 'medical'],
    tags: ['insurance-accepted', 'emergency', 'family-friendly'],
    features: ['online-scheduling', 'digital-xrays', 'sedation'],
    amenities: ['parking', 'wheelchair-accessible', 'wifi'],
    pricingRange: 'EXPENSIVE',
    averageRating: 4.7,
    reviewCount: 94,
    isSponsored: false,
    status: 'PUBLISHED',
    createdAt: '2024-01-12T13:00:00Z',
    updatedAt: '2024-01-21T10:30:00Z',
  },
  {
    id: '6',
    name: 'Tony\'s Pizza Palace',
    description: 'New York style pizza with thin crust and fresh toppings. Late night delivery available.',
    slug: 'tonys-pizza-palace',
    street: '987 Broadway',
    city: 'New York',
    state: 'NY',
    zipCode: '10010',
    latitude: 40.7505,
    longitude: -73.9934,
    phone: '(555) 678-9012',
    email: 'orders@tonyspizza.com',
    website: 'https://tonyspizza.com',
    images: ['/images/pizza1.jpg'],
    categories: ['restaurants', 'pizza', 'italian'],
    tags: ['late-night', 'delivery', 'ny-style'],
    features: ['delivery', 'takeout', 'online-ordering'],
    amenities: ['parking', 'wifi'],
    pricingRange: 'BUDGET',
    averageRating: 4.1,
    reviewCount: 312,
    isSponsored: false,
    status: 'PUBLISHED',
    createdAt: '2024-01-03T18:00:00Z',
    updatedAt: '2024-01-17T20:15:00Z',
  },
  {
    id: '7',
    name: 'FreshMart Grocery',
    description: 'Full-service grocery store with fresh produce, organic options, and everyday essentials.',
    slug: 'freshmart-grocery',
    street: '159 Second Avenue',
    city: 'New York',
    state: 'NY',
    zipCode: '10003',
    latitude: 40.7282,
    longitude: -73.9942,
    phone: '(555) 789-0123',
    email: 'info@freshmart.com',
    website: 'https://freshmart.com',
    images: ['/images/grocery1.jpg'],
    categories: ['grocery', 'food', 'shopping'],
    tags: ['organic', 'fresh', 'local'],
    features: ['delivery', 'curbside-pickup', 'loyalty-program'],
    amenities: ['parking', 'wheelchair-accessible', 'pharmacy'],
    pricingRange: 'MODERATE',
    averageRating: 4.0,
    reviewCount: 78,
    isSponsored: true,
    sponsoredRank: 3,
    sponsoredTier: 'BRONZE',
    status: 'PUBLISHED',
    createdAt: '2024-01-07T07:00:00Z',
    updatedAt: '2024-01-16T14:20:00Z',
  },
  {
    id: '8',
    name: 'PowerFit Gym',
    description: 'State-of-the-art fitness facility with modern equipment, group classes, and personal training.',
    slug: 'powerfit-gym',
    street: '753 Lexington Avenue',
    city: 'New York',
    state: 'NY',
    zipCode: '10022',
    latitude: 40.7614,
    longitude: -73.9776,
    phone: '(555) 890-1234',
    email: 'membership@powerfitgym.com',
    website: 'https://powerfitgym.com',
    images: ['/images/gym1.jpg'],
    categories: ['fitness', 'gym', 'health'],
    tags: ['24-hour', 'personal-training', 'classes'],
    features: ['membership', 'personal-training', 'group-classes'],
    amenities: ['parking', 'locker-rooms', 'showers'],
    pricingRange: 'MODERATE',
    averageRating: 4.4,
    reviewCount: 167,
    isSponsored: false,
    status: 'PUBLISHED',
    createdAt: '2024-01-09T06:00:00Z',
    updatedAt: '2024-01-23T09:45:00Z',
  },
];

export const demoCategories = [
  { id: '1', name: 'Restaurants', slug: 'restaurants', count: 3 },
  { id: '2', name: 'Coffee & Cafes', slug: 'coffee', count: 1 },
  { id: '3', name: 'Beauty & Spa', slug: 'beauty', count: 1 },
  { id: '4', name: 'Automotive', slug: 'automotive', count: 1 },
  { id: '5', name: 'Healthcare', slug: 'healthcare', count: 1 },
  { id: '6', name: 'Shopping', slug: 'shopping', count: 1 },
  { id: '7', name: 'Fitness', slug: 'fitness', count: 1 },
];

export const demoTags = [
  'family-friendly',
  'romantic',
  'outdoor-seating',
  'wifi',
  'study-friendly',
  'local',
  'luxury',
  'appointments-only',
  'experienced',
  'quick-service',
  'certified',
  'warranty',
  'insurance-accepted',
  'emergency',
  'late-night',
  'delivery',
  'ny-style',
  'organic',
  'fresh',
  '24-hour',
  'personal-training',
  'classes',
];

export const demoFeatures = [
  'takeout',
  'delivery',
  'reservations',
  'mobile-ordering',
  'loyalty-program',
  'online-booking',
  'consultations',
  'color-specialist',
  'while-you-wait',
  'shuttle-service',
  'estimates',
  'online-scheduling',
  'digital-xrays',
  'sedation',
  'online-ordering',
  'curbside-pickup',
  'membership',
  'personal-training',
  'group-classes',
];

export const demoAmenities = [
  'parking',
  'wifi',
  'wheelchair-accessible',
  'outdoor-seating',
  'waiting-area',
  'pharmacy',
  'locker-rooms',
  'showers',
];